on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          architecture: 'x64'
          bundler-cache: true
      - name: Build
        run: bundle exec middleman build
      - name: Publish
        run: |
          rm -rf build
          git config --global user.email "shaunkenclark@gmail.com"
          git config --global user.name "shaunkenclark"
          git remote set-url origin https://nobody:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          bundle exec rake publish
        if: github.ref == 'refs/heads/main'
