on:
  pull_request:
    branches:
      - source
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
          architecture: 'x64'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build
        run: bundle exec middleman build
      - name: Publish
        run: |
          rm -rf build
          git config --global user.email "10130616+shaunkenclark@users.noreply.github.com"
          git config --global user.name "shaunkenclark"
          git remote set-url origin https://nobody:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          bundle exec rake publish
        if: github.ref == 'refs/head/source'
